"""add warehouse models

Revision ID: f51ad9f5b634
Revises: 72d7f7a5b35f
Create Date: 2026-09-02 01:02:25.114996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51ad9f5b634'
down_revision: Union[str, Sequence[str], None] = '72d7f7a5b35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_info', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.Enum('L', 'M', 'SHT', 'KG', 'M_SQR', 'T', name='unit'), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('one_price', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('sum_price', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('PRIHOD', 'RASHOD', 'VOZVRAT', 'KORREKTIROVKA', name='operationtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_operations')
    op.drop_table('raw_materials')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
